//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supplements.ServiceAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultDescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResultDescription()
        {
            this.DoseResultDescriptions = new HashSet<DoseResultDescription>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> DoseResultDescription_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoseResultDescription> DoseResultDescriptions { get; set; }
        public virtual DoseResultDescription DoseResultDescription { get; set; }
    }
}
